/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.islandstudio.paradiseresort.ui.panels;

import com.islandstudio.paradiseresort.event.GUIEventHandler;
import com.islandstudio.paradiseresort.ui.CustomRoundBorder;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.io.IOException;
import java.util.Objects;

/**
 *
 * @author Kah Heng Siew
 */
public class BookingDetailsMenuUI extends javax.swing.JPanel {

    /**
     * Creates new form BookingDetailsUI
     */
    public BookingDetailsMenuUI() {
        initComponents();
    }


    @Override
    protected void paintComponent(java.awt.Graphics g) {
        try {
            Image img = ImageIO.read(Objects.requireNonNull(getClass().getClassLoader().getResource("resources/images/home_background.png")));
            g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), null);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Image not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeLogoPanel = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                try {
                    Image img = ImageIO.read(Objects.requireNonNull(getClass().getClassLoader().getResource("resources/images/logo.png")));
                    g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), null);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        };
        bookingDetailsComponentsPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                Graphics2D gpd = (Graphics2D) g;

                Color bgColor_1 = new Color(255, 255, 255, 52);

                gpd.setPaint(bgColor_1);
                gpd.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 20, 20);
            }

            @Override
            public void setBorder(Border border) {
                super.setBorder(new CustomRoundBorder(20));
            }
        };
        manageBookingDetailsBTN = new com.k33ptoo.components.KButton();
        backHomeBTN = new com.k33ptoo.components.KButton();
        viewReceiptBTN = new com.k33ptoo.components.KButton();
        bookingDetailsTitle = new javax.swing.JLabel();
        homeLogoText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout homeLogoPanelLayout = new javax.swing.GroupLayout(homeLogoPanel);
        homeLogoPanel.setLayout(homeLogoPanelLayout);
        homeLogoPanelLayout.setHorizontalGroup(
            homeLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        homeLogoPanelLayout.setVerticalGroup(
            homeLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        manageBookingDetailsBTN.setBorder(null);
        manageBookingDetailsBTN.setText("Manage Booking Details");
        manageBookingDetailsBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        manageBookingDetailsBTN.setkBackGroundColor(new java.awt.Color(102, 0, 255));
        manageBookingDetailsBTN.setkBorderRadius(30);
        manageBookingDetailsBTN.setkEndColor(new java.awt.Color(204, 204, 204));
        manageBookingDetailsBTN.setkForeGround(new java.awt.Color(0, 0, 0));
        manageBookingDetailsBTN.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        manageBookingDetailsBTN.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        manageBookingDetailsBTN.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        manageBookingDetailsBTN.setkStartColor(new java.awt.Color(153, 153, 153));
        manageBookingDetailsBTN.setOpaque(false);
        manageBookingDetailsBTN.addActionListener(GUIEventHandler.actionListener);

        backHomeBTN.setBorder(null);
        backHomeBTN.setText("Back to Home");
        backHomeBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        backHomeBTN.setkBackGroundColor(new java.awt.Color(102, 0, 255));
        backHomeBTN.setkBorderRadius(30);
        backHomeBTN.setkEndColor(new java.awt.Color(204, 204, 204));
        backHomeBTN.setkForeGround(new java.awt.Color(0, 0, 0));
        backHomeBTN.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        backHomeBTN.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        backHomeBTN.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        backHomeBTN.setkIndicatorThickness(0);
        backHomeBTN.setkStartColor(new java.awt.Color(153, 153, 153));
        backHomeBTN.addActionListener(GUIEventHandler.actionListener);

        viewReceiptBTN.setBorder(null);
        viewReceiptBTN.setText("View Receipt");
        viewReceiptBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        viewReceiptBTN.setkBackGroundColor(new java.awt.Color(102, 0, 255));
        viewReceiptBTN.setkBorderRadius(30);
        viewReceiptBTN.setkEndColor(new java.awt.Color(204, 204, 204));
        viewReceiptBTN.setkForeGround(new java.awt.Color(0, 0, 0));
        viewReceiptBTN.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        viewReceiptBTN.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        viewReceiptBTN.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        viewReceiptBTN.setkStartColor(new java.awt.Color(153, 153, 153));
        viewReceiptBTN.addActionListener(GUIEventHandler.actionListener);

        bookingDetailsTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        bookingDetailsTitle.setForeground(new java.awt.Color(255, 255, 255));
        bookingDetailsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingDetailsTitle.setText("Booking Details");

        javax.swing.GroupLayout bookingDetailsComponentsPanelLayout = new javax.swing.GroupLayout(bookingDetailsComponentsPanel);
        bookingDetailsComponentsPanel.setLayout(bookingDetailsComponentsPanelLayout);
        bookingDetailsComponentsPanelLayout.setHorizontalGroup(
            bookingDetailsComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingDetailsComponentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageBookingDetailsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(bookingDetailsComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookingDetailsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewReceiptBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(backHomeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookingDetailsComponentsPanelLayout.setVerticalGroup(
            bookingDetailsComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingDetailsComponentsPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(bookingDetailsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(bookingDetailsComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageBookingDetailsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewReceiptBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backHomeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        homeLogoText.setFont(new java.awt.Font("Brush Script MT", 0, 70)); // NOI18N
        homeLogoText.setForeground(new java.awt.Color(255, 153, 0));
        homeLogoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLogoText.setText("Paradise");
        homeLogoText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resort");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(bookingDetailsComponentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(homeLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(homeLogoText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(homeLogoText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(bookingDetailsComponentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static com.k33ptoo.components.KButton backHomeBTN;
    private javax.swing.JPanel bookingDetailsComponentsPanel;
    private javax.swing.JLabel bookingDetailsTitle;
    private javax.swing.JPanel homeLogoPanel;
    private javax.swing.JLabel homeLogoText;
    private javax.swing.JLabel jLabel1;
    private static com.k33ptoo.components.KButton manageBookingDetailsBTN;
    private static com.k33ptoo.components.KButton viewReceiptBTN;
    // End of variables declaration//GEN-END:variables

    public static JButton getBackHomeBTN() {
        return backHomeBTN;
    }

    public static JButton getManageBookingDetailsBTN() {
        return manageBookingDetailsBTN;
    }

    public static JButton getViewReceiptBTN() {
        return viewReceiptBTN;
    }

}
