/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.islandstudio.paradiseresort.ui.panels;

import com.islandstudio.paradiseresort.event.GUIEventHandler;
import com.islandstudio.paradiseresort.ui.CustomRoundBorder;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.io.IOException;
import java.util.Objects;

/**
 *
 * @author Kah Heng Siew
 */
public class HomeUI extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public HomeUI() {
        initComponents();
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        try {
            Image img = ImageIO.read(Objects.requireNonNull(getClass().getClassLoader().getResource("resources/images/home_background.png")));
            g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), null);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Image not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeLogoPanel = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                try {
                    Image img = ImageIO.read(Objects.requireNonNull(getClass().getClassLoader().getResource("resources/images/logo.png")));
                    g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), null);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        };
        homeComponentsPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                Graphics2D gpd = (Graphics2D) g;

                Color bgColor_1 = new Color(255, 255, 255, 52);

                gpd.setPaint(bgColor_1);
                gpd.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 20, 20);
            }

            @Override
            public void setBorder(Border border) {
                super.setBorder(new CustomRoundBorder(20));
            }
        };
        bookRoomBTN = new com.k33ptoo.components.KButton();
        logoutBTN = new com.k33ptoo.components.KButton();
        bookingDetailsBTN = new com.k33ptoo.components.KButton();
        greetingLabel = new javax.swing.JLabel();
        homeLogoText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        versionTitle = new javax.swing.JLabel();
        versionTitle1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1500, 800));

        javax.swing.GroupLayout homeLogoPanelLayout = new javax.swing.GroupLayout(homeLogoPanel);
        homeLogoPanel.setLayout(homeLogoPanelLayout);
        homeLogoPanelLayout.setHorizontalGroup(
            homeLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        homeLogoPanelLayout.setVerticalGroup(
            homeLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        bookRoomBTN.setBorder(null);
        bookRoomBTN.setText("Book a Room");
        bookRoomBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        bookRoomBTN.setkBackGroundColor(new java.awt.Color(102, 0, 255));
        bookRoomBTN.setkBorderRadius(30);
        bookRoomBTN.setkEndColor(new java.awt.Color(204, 204, 204));
        bookRoomBTN.setkForeGround(new java.awt.Color(0, 0, 0));
        bookRoomBTN.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        bookRoomBTN.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        bookRoomBTN.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        bookRoomBTN.setkStartColor(new java.awt.Color(153, 153, 153));
        bookRoomBTN.setOpaque(false);
        bookRoomBTN.addActionListener(GUIEventHandler.actionListener);

        logoutBTN.setBorder(null);
        logoutBTN.setText("Log Out");
        logoutBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        logoutBTN.setkBackGroundColor(new java.awt.Color(102, 0, 255));
        logoutBTN.setkBorderRadius(30);
        logoutBTN.setkEndColor(new java.awt.Color(204, 204, 204));
        logoutBTN.setkForeGround(new java.awt.Color(0, 0, 0));
        logoutBTN.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        logoutBTN.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        logoutBTN.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        logoutBTN.setkStartColor(new java.awt.Color(153, 153, 153));
        logoutBTN.addActionListener(GUIEventHandler.actionListener);

        bookingDetailsBTN.setBorder(null);
        bookingDetailsBTN.setText("Booking Details");
        bookingDetailsBTN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        bookingDetailsBTN.setkBackGroundColor(new java.awt.Color(102, 0, 255));
        bookingDetailsBTN.setkBorderRadius(30);
        bookingDetailsBTN.setkEndColor(new java.awt.Color(204, 204, 204));
        bookingDetailsBTN.setkForeGround(new java.awt.Color(0, 0, 0));
        bookingDetailsBTN.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        bookingDetailsBTN.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        bookingDetailsBTN.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        bookingDetailsBTN.setkStartColor(new java.awt.Color(153, 153, 153));
        bookingDetailsBTN.addActionListener(GUIEventHandler.actionListener);

        greetingLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        greetingLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingLabel.setText("Welcome back, user!");

        javax.swing.GroupLayout homeComponentsPanelLayout = new javax.swing.GroupLayout(homeComponentsPanel);
        homeComponentsPanel.setLayout(homeComponentsPanelLayout);
        homeComponentsPanelLayout.setHorizontalGroup(
            homeComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeComponentsPanelLayout.createSequentialGroup()
                .addGroup(homeComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeComponentsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookRoomBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bookingDetailsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(logoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeComponentsPanelLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(greetingLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeComponentsPanelLayout.setVerticalGroup(
            homeComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeComponentsPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(greetingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(homeComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookRoomBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingDetailsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        homeLogoText.setFont(new java.awt.Font("Brush Script MT", 0, 70)); // NOI18N
        homeLogoText.setForeground(new java.awt.Color(255, 153, 0));
        homeLogoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLogoText.setText("Paradise");
        homeLogoText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resort");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        versionTitle.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        versionTitle.setForeground(new java.awt.Color(255, 255, 255));
        versionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionTitle.setText("Paradise Resort v1.0.0");

        versionTitle1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        versionTitle1.setForeground(new java.awt.Color(255, 255, 255));
        versionTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionTitle1.setText("© Island Studio™ 2022");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(homeLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(homeLogoText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(homeComponentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(versionTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(versionTitle1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(homeLogoText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(homeComponentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionTitle)
                    .addComponent(versionTitle1)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static com.k33ptoo.components.KButton bookRoomBTN;
    private static com.k33ptoo.components.KButton bookingDetailsBTN;
    private static javax.swing.JLabel greetingLabel;
    private javax.swing.JPanel homeComponentsPanel;
    private javax.swing.JPanel homeLogoPanel;
    private javax.swing.JLabel homeLogoText;
    private javax.swing.JLabel jLabel1;
    private static com.k33ptoo.components.KButton logoutBTN;
    private javax.swing.JLabel versionTitle;
    private javax.swing.JLabel versionTitle1;
    // End of variables declaration//GEN-END:variables

    public static JButton getLogoutBTN() {
        return logoutBTN;
    }

    public static JLabel getGreetingLabel() {
        return greetingLabel;
    }

    public static JButton getBookRoomBTN() {
        return bookRoomBTN;
    }

    public static JButton getBookingDetailsBTN() {
        return bookingDetailsBTN;
    }
}
