/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.islandstudio.paradiseresort.ui.panels;

import com.islandstudio.paradiseresort.event.GUIEventHandler;
import com.islandstudio.paradiseresort.ui.CustomRoundBorder;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.io.IOException;
import java.util.Objects;

/**
 *
 * @author Kah Heng Siew
 */
public class ReceiptUI extends javax.swing.JPanel {

    /**
     * Creates new form ViewReceiptUI
     */
    public ReceiptUI() {
        initComponents();
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        try {
            Image img = ImageIO.read(Objects.requireNonNull(getClass().getClassLoader().getResource("resources/images/home_background.png")));
            g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), null);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Image not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitlePanel = new javax.swing.JPanel();
        viewRceiptTitle = new javax.swing.JLabel();
        bookingSelectionPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                Graphics2D gpd = (Graphics2D) g;

                Color bgColor_1 = new Color(255, 255, 255, 52);

                gpd.setPaint(bgColor_1);
                gpd.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 20, 20);
            }

            @Override
            public void setBorder(Border border) {
                super.setBorder(new CustomRoundBorder(20));
            }
        };
        bookingListTitle = new javax.swing.JLabel();
        searchTitle = new javax.swing.JLabel();
        searchBTN = new javax.swing.JButton();
        bookingDetailTableScrollFrame = new javax.swing.JScrollPane();
        receiptTable = new javax.swing.JTable();
        selectBookingDetailTitle = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        clearSearchBTN = new javax.swing.JButton();
        backViewReceiptBTN = new javax.swing.JButton();
        receiptFrame = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                Graphics2D gpd = (Graphics2D) g;

                Color bgColor_1 = new Color(255, 255, 255, 52);

                gpd.setPaint(bgColor_1);
                gpd.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 20, 20);
            }

            @Override
            public void setBorder(Border border) {
                super.setBorder(new CustomRoundBorder(20));
            }
        };
        receiptPanel = new javax.swing.JPanel();
        receiptLogoPanel = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                try {
                    Image img = ImageIO.read(Objects.requireNonNull(getClass().getClassLoader().getResource("resources/images/logo.png")));
                    g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), null);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        };
        homeLogoText = new javax.swing.JLabel();
        homeLogoText2 = new javax.swing.JLabel();
        receiptNoTtitle = new javax.swing.JLabel();
        receiptNoField = new javax.swing.JLabel();
        customerICTitle = new javax.swing.JLabel();
        customerNameTitle = new javax.swing.JLabel();
        customerContactTitle = new javax.swing.JLabel();
        customerEmailTitle = new javax.swing.JLabel();
        roomTitle = new javax.swing.JLabel();
        roomTypeTitle = new javax.swing.JLabel();
        checkInDateTitle = new javax.swing.JLabel();
        checkOutDateTitle = new javax.swing.JLabel();
        totalNightsTitle = new javax.swing.JLabel();
        receiptInnerBox = new javax.swing.JPanel();
        serviceTaxTitle = new javax.swing.JLabel();
        totalTitle = new javax.swing.JLabel();
        tourismTaxTitle = new javax.swing.JLabel();
        grandTotalTitle = new javax.swing.JLabel();
        totalField = new javax.swing.JLabel();
        serviceTaxField = new javax.swing.JLabel();
        tourismTaxField = new javax.swing.JLabel();
        grandTotalField = new javax.swing.JLabel();
        customerICField = new javax.swing.JLabel();
        customerNameField = new javax.swing.JLabel();
        customerContactField = new javax.swing.JLabel();
        customerEmailField = new javax.swing.JLabel();
        roomField = new javax.swing.JLabel();
        roomTypeField = new javax.swing.JLabel();
        checkInDateField = new javax.swing.JLabel();
        checkOutDateField = new javax.swing.JLabel();
        totalNightsField = new javax.swing.JLabel();

        mainTitlePanel.setOpaque(false);

        viewRceiptTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        viewRceiptTitle.setForeground(new java.awt.Color(204, 204, 204));
        viewRceiptTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewRceiptTitle.setText("View Receipt");

        javax.swing.GroupLayout mainTitlePanelLayout = new javax.swing.GroupLayout(mainTitlePanel);
        mainTitlePanel.setLayout(mainTitlePanelLayout);
        mainTitlePanelLayout.setHorizontalGroup(
            mainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainTitlePanelLayout.createSequentialGroup()
                .addGap(639, 639, 639)
                .addComponent(viewRceiptTitle)
                .addContainerGap(643, Short.MAX_VALUE))
        );
        mainTitlePanelLayout.setVerticalGroup(
            mainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainTitlePanelLayout.createSequentialGroup()
                .addComponent(viewRceiptTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bookingSelectionPanel.setOpaque(false);

        bookingListTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bookingListTitle.setForeground(new java.awt.Color(255, 255, 255));
        bookingListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingListTitle.setText("Receipt List");

        searchTitle.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        searchTitle.setForeground(new java.awt.Color(255, 255, 255));
        searchTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchTitle.setText("Search:");

        searchBTN.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        searchBTN.setText("Search");
        searchBTN.setActionCommand("Search Receipt");
        searchBTN.addActionListener(GUIEventHandler.actionListener);

        receiptTable.addMouseListener(GUIEventHandler.mouseListener);
        receiptTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        receiptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookingUUID", "Receipt No.", "Customer IC/Passport No.", "Customer Name", "Customer Contact", "Customer Email", "Room", "Room Type", "Check In Date", "Check Out Date", "Total Nights", "Total", "Service Tax", "Tourism Tax", "Grand Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        receiptTable.getTableHeader().setReorderingAllowed(false);
        bookingDetailTableScrollFrame.setViewportView(receiptTable);

        selectBookingDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        selectBookingDetailTitle.setForeground(new java.awt.Color(255, 255, 255));
        selectBookingDetailTitle.setText("Select Customer Receipt:");

        searchField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        clearSearchBTN.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        clearSearchBTN.setText("Clear");
        clearSearchBTN.setActionCommand("Clear Search Receipt");
        clearSearchBTN.addActionListener(GUIEventHandler.actionListener);

        backViewReceiptBTN.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        backViewReceiptBTN.setText("Back");
        backViewReceiptBTN.setActionCommand("Back to Booking Details");
        backViewReceiptBTN.addActionListener(GUIEventHandler.actionListener);

        javax.swing.GroupLayout bookingSelectionPanelLayout = new javax.swing.GroupLayout(bookingSelectionPanel);
        bookingSelectionPanel.setLayout(bookingSelectionPanelLayout);
        bookingSelectionPanelLayout.setHorizontalGroup(
            bookingSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingSelectionPanelLayout.createSequentialGroup()
                .addGroup(bookingSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingSelectionPanelLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(bookingListTitle))
                    .addGroup(bookingSelectionPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(bookingSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bookingSelectionPanelLayout.createSequentialGroup()
                                .addComponent(searchTitle)
                                .addGap(9, 9, 9)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearSearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bookingDetailTableScrollFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectBookingDetailTitle)))
                    .addGroup(bookingSelectionPanelLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(backViewReceiptBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        bookingSelectionPanelLayout.setVerticalGroup(
            bookingSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingListTitle)
                .addGap(43, 43, 43)
                .addGroup(bookingSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTitle)
                    .addComponent(clearSearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(selectBookingDetailTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingDetailTableScrollFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backViewReceiptBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        receiptFrame.setOpaque(false);

        receiptPanel.setBackground(new java.awt.Color(255, 234, 209));
        receiptPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 237, 207), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout receiptLogoPanelLayout = new javax.swing.GroupLayout(receiptLogoPanel);
        receiptLogoPanel.setLayout(receiptLogoPanelLayout);
        receiptLogoPanelLayout.setHorizontalGroup(
            receiptLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        receiptLogoPanelLayout.setVerticalGroup(
            receiptLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        homeLogoText.setFont(new java.awt.Font("Brush Script MT", 0, 48)); // NOI18N
        homeLogoText.setForeground(new java.awt.Color(255, 153, 0));
        homeLogoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLogoText.setText("Paradise");
        homeLogoText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        homeLogoText2.setFont(new java.awt.Font("Brush Script MT", 0, 48)); // NOI18N
        homeLogoText2.setForeground(new java.awt.Color(0, 153, 255));
        homeLogoText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLogoText2.setText("Resort");
        homeLogoText2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        receiptNoTtitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        receiptNoTtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receiptNoTtitle.setText("Receipt No.");

        receiptNoField.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        receiptNoField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receiptNoField.setText("   ");

        customerICTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerICTitle.setText("Customer IC/Passport Number  :");

        customerNameTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerNameTitle.setText("Customer Name                          :");

        customerContactTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerContactTitle.setText("Customer Contact                       :");

        customerEmailTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerEmailTitle.setText("Customer Email                           :");

        roomTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomTitle.setText("Room                                           :");

        roomTypeTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomTypeTitle.setText("Room Type                                  :");

        checkInDateTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInDateTitle.setText("Check In Date                             :");

        checkOutDateTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkOutDateTitle.setText("Check Out Date                          :");

        totalNightsTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalNightsTitle.setText("Total Nights                                :");

        receiptInnerBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        receiptInnerBox.setOpaque(false);

        serviceTaxTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        serviceTaxTitle.setText("Service Tax (10% of Total)     :");

        totalTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalTitle.setText("Total                                         :");

        tourismTaxTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tourismTaxTitle.setText("Tourism Tax (RM 10 / night)  :");

        grandTotalTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        grandTotalTitle.setText("Grand Total                              :");

        totalField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalField.setText("   ");

        serviceTaxField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        serviceTaxField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serviceTaxField.setText("   ");

        tourismTaxField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tourismTaxField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tourismTaxField.setText("   ");

        grandTotalField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        grandTotalField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grandTotalField.setText("   ");

        javax.swing.GroupLayout receiptInnerBoxLayout = new javax.swing.GroupLayout(receiptInnerBox);
        receiptInnerBox.setLayout(receiptInnerBoxLayout);
        receiptInnerBoxLayout.setHorizontalGroup(
            receiptInnerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptInnerBoxLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(receiptInnerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tourismTaxTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grandTotalTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serviceTaxTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(receiptInnerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serviceTaxField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tourismTaxField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grandTotalField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        receiptInnerBoxLayout.setVerticalGroup(
            receiptInnerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiptInnerBoxLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(receiptInnerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTitle)
                    .addComponent(totalField))
                .addGap(18, 18, 18)
                .addGroup(receiptInnerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceTaxTitle)
                    .addComponent(serviceTaxField))
                .addGap(18, 18, 18)
                .addGroup(receiptInnerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tourismTaxTitle)
                    .addComponent(tourismTaxField))
                .addGap(18, 18, 18)
                .addGroup(receiptInnerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grandTotalTitle)
                    .addComponent(grandTotalField))
                .addGap(28, 28, 28))
        );

        customerICField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerICField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerICField.setText("   ");

        customerNameField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerNameField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerNameField.setText("   ");

        customerContactField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerContactField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerContactField.setText("   ");

        customerEmailField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerEmailField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerEmailField.setText("   ");

        roomField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomField.setText("   ");

        roomTypeField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomTypeField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomTypeField.setText("   ");

        checkInDateField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInDateField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkInDateField.setText("   ");

        checkOutDateField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkOutDateField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkOutDateField.setText("   ");

        totalNightsField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalNightsField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalNightsField.setText("   ");

        javax.swing.GroupLayout receiptPanelLayout = new javax.swing.GroupLayout(receiptPanel);
        receiptPanel.setLayout(receiptPanelLayout);
        receiptPanelLayout.setHorizontalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receiptInnerBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiptPanelLayout.createSequentialGroup()
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(receiptPanelLayout.createSequentialGroup()
                        .addComponent(receiptLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(receiptPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(homeLogoText))
                            .addGroup(receiptPanelLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(homeLogoText2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(receiptNoTtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(receiptNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(receiptPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerICTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerContactTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerEmailTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roomTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roomTypeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkInDateTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkOutDateTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalNightsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerICField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerContactField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(customerEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roomField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roomTypeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkInDateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkOutDateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalNightsField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
        );
        receiptPanelLayout.setVerticalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(receiptPanelLayout.createSequentialGroup()
                            .addComponent(homeLogoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(homeLogoText2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))
                        .addComponent(receiptLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(receiptPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(receiptNoTtitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiptNoField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerICTitle)
                    .addComponent(customerICField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameTitle)
                    .addComponent(customerNameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerContactTitle)
                    .addComponent(customerContactField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerEmailTitle)
                    .addComponent(customerEmailField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTitle)
                    .addComponent(roomField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypeTitle)
                    .addComponent(roomTypeField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInDateTitle)
                    .addComponent(checkInDateField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutDateTitle)
                    .addComponent(checkOutDateField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalNightsTitle)
                    .addComponent(totalNightsField))
                .addGap(18, 18, 18)
                .addComponent(receiptInnerBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout receiptFrameLayout = new javax.swing.GroupLayout(receiptFrame);
        receiptFrame.setLayout(receiptFrameLayout);
        receiptFrameLayout.setHorizontalGroup(
            receiptFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiptFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        receiptFrameLayout.setVerticalGroup(
            receiptFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bookingSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receiptFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton backViewReceiptBTN;
    private javax.swing.JScrollPane bookingDetailTableScrollFrame;
    private javax.swing.JLabel bookingListTitle;
    private javax.swing.JPanel bookingSelectionPanel;
    private static javax.swing.JLabel checkInDateField;
    private javax.swing.JLabel checkInDateTitle;
    private static javax.swing.JLabel checkOutDateField;
    private javax.swing.JLabel checkOutDateTitle;
    private static javax.swing.JButton clearSearchBTN;
    private static javax.swing.JLabel customerContactField;
    private javax.swing.JLabel customerContactTitle;
    private static javax.swing.JLabel customerEmailField;
    private javax.swing.JLabel customerEmailTitle;
    private static javax.swing.JLabel customerICField;
    private javax.swing.JLabel customerICTitle;
    private static javax.swing.JLabel customerNameField;
    private javax.swing.JLabel customerNameTitle;
    private static javax.swing.JLabel grandTotalField;
    private javax.swing.JLabel grandTotalTitle;
    private javax.swing.JLabel homeLogoText;
    private javax.swing.JLabel homeLogoText2;
    private javax.swing.JPanel mainTitlePanel;
    private javax.swing.JPanel receiptFrame;
    private javax.swing.JPanel receiptInnerBox;
    private javax.swing.JPanel receiptLogoPanel;
    private static javax.swing.JLabel receiptNoField;
    private javax.swing.JLabel receiptNoTtitle;
    private static javax.swing.JPanel receiptPanel;
    private static javax.swing.JTable receiptTable;
    private static javax.swing.JLabel roomField;
    private javax.swing.JLabel roomTitle;
    private static javax.swing.JLabel roomTypeField;
    private javax.swing.JLabel roomTypeTitle;
    private static javax.swing.JButton searchBTN;
    private static javax.swing.JTextField searchField;
    private javax.swing.JLabel searchTitle;
    private javax.swing.JLabel selectBookingDetailTitle;
    private static javax.swing.JLabel serviceTaxField;
    private javax.swing.JLabel serviceTaxTitle;
    private static javax.swing.JLabel totalField;
    private static javax.swing.JLabel totalNightsField;
    private javax.swing.JLabel totalNightsTitle;
    private javax.swing.JLabel totalTitle;
    private static javax.swing.JLabel tourismTaxField;
    private javax.swing.JLabel tourismTaxTitle;
    private javax.swing.JLabel viewRceiptTitle;
    // End of variables declaration//GEN-END:variables

    public static JButton getBackViewReceiptBTN() {
        return backViewReceiptBTN;
    }

    public static JButton getClearSearchBTN() {
        return clearSearchBTN;
    }

    public static JButton getSearchBTN() {
        return searchBTN;
    }

    public static JTextField getSearchField() {
        return searchField;
    }

    public static JTable getReceiptTable() {
        return receiptTable;
    }

    public static JLabel getReceiptNoField() {
        return receiptNoField;
    }

    public static JLabel getCustomerICField() {
        return customerICField;
    }

    public static JLabel getCustomerNameField() {
        return customerNameField;
    }

    public static JLabel getCustomerContactField() {
        return customerContactField;
    }

    public static JLabel getCustomerEmailField() {
        return customerEmailField;
    }

    public static JLabel getRoomField() {
        return roomField;
    }

    public static JLabel getRoomTypeField() {
        return roomTypeField;
    }

    public static JLabel getCheckInDateField() {
        return checkInDateField;
    }

    public static JLabel getCheckOutDateField() {
        return checkOutDateField;
    }

    public static JLabel getTotalNightsField() {
        return totalNightsField;
    }

    public static JLabel getTotalField() {
        return totalField;
    }

    public static JLabel getServiceTaxField() {
        return serviceTaxField;
    }

    public static JLabel getTourismTaxField() {
        return tourismTaxField;
    }

    public static JLabel getGrandTotalField() {
        return grandTotalField;
    }
}
